//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_table
    {
        public car_table()
        {
            this.parts_table = new HashSet<parts_table>();
        }
    
        public int car_id { get; set; }
        public Nullable<int> car_year { get; set; }
        public string car_make { get; set; }
        public string car_model { get; set; }
    
        public virtual ICollection<parts_table> parts_table { get; set; }
    }
}
