//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_table
    {
        public invoice_table()
        {
            this.orders_table = new HashSet<orders_table>();
        }
    
        public int invoice_num { get; set; }
        public Nullable<decimal> invoice_total { get; set; }
        public Nullable<int> user_num { get; set; }
        public string invoice_filled { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
    
        public virtual users_table users_table { get; set; }
        public virtual ICollection<orders_table> orders_table { get; set; }
    }
}
