//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parts_table
    {
        public parts_table()
        {
            this.cart_table = new HashSet<cart_table>();
            this.orders_table = new HashSet<orders_table>();
        }
    
        public int part_number { get; set; }
        public string part_description { get; set; }
        public Nullable<int> car_id { get; set; }
        public Nullable<int> part_category { get; set; }
        public Nullable<int> part_stock { get; set; }
        public Nullable<double> part_price { get; set; }
    
        public virtual car_table car_table { get; set; }
        public virtual ICollection<cart_table> cart_table { get; set; }
        public virtual ICollection<orders_table> orders_table { get; set; }
    }
}
