//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_table
    {
        public string cart_name { get; set; }
        public Nullable<int> cart_tied_to_user { get; set; }
        public Nullable<int> part_number { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int cart_instance_id { get; set; }
    
        public virtual parts_table parts_table { get; set; }
    }
}
