//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class capstoneEntities : DbContext
    {
        public capstoneEntities()
            : base("name=capstoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<appointments_table> appointments_table { get; set; }
        public DbSet<car_table> car_table { get; set; }
        public DbSet<cart_table> cart_table { get; set; }
        public DbSet<invoice_table> invoice_table { get; set; }
        public DbSet<message_table> message_table { get; set; }
        public DbSet<orders_table> orders_table { get; set; }
        public DbSet<parts_table> parts_table { get; set; }
        public DbSet<users_table> users_table { get; set; }
    }
}
