//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_table
    {
        public int message_id { get; set; }
        public Nullable<int> created_by_user_num { get; set; }
        public string user_message { get; set; }
        public Nullable<System.DateTime> message_time { get; set; }
        public string message_status { get; set; }
    
        public virtual users_table users_table { get; set; }
    }
}
