//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_table
    {
        public int order_num { get; set; }
        public Nullable<int> invoice_num { get; set; }
        public int part_num { get; set; }
        public int quantity { get; set; }
    
        public virtual parts_table parts_table { get; set; }
        public virtual invoice_table invoice_table { get; set; }
    }
}
